# Generated by Django 5.0.4 on 2024-07-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eml_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='location',
            field=models.CharField(default='Location', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='mobile',
            field=models.CharField(default='9965610028', max_length=15),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='occupation',
            field=models.CharField(default='Occupation', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='feedback',
            field=models.TextField(blank=True, default='Location', null=True),
        ),
    ]
